# Question 1

In [17]:
import numpy as np
arr=np.array(range(2,51,3))
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question 2

In [43]:
import numpy as np
list_1=[]
list_2=[]
a=0
b=0
print("Enter list_1 elements")
while a<5:
    ip=int(input())
    list_1.append(ip)
    a=a+1
print("Enter list_2 elements")
while b<5:
    ip1=int(input())
    list_2.append(ip1)
    b=b+1

array_1=np.array(list_1)
array_2=np.array(list_2)
print("Concatenated array:",np.concatenate((array_1,array_2)))
print("Sorted array:",np.sort(np.concatenate((array_1,array_2))))

Enter list_1 elements
187
65
10
378
9056
Enter list_2 elements
0
194
367
850
30
Concatenated array: [ 187   65   10  378 9056    0  194  367  850   30]
Sorted array: [   0   10   30   65  187  194  367  378  850 9056]


# Question 3

In [47]:
import numpy as np
arr=np.array([[4,5,6],[1,9,8]])
print(arr.ndim)
print(arr.size)

2
6


# Question 4

In [51]:
import numpy as np
arr=np.arange(0,5)
print(arr)
print(arr.ndim)
new_arr = arr[np.newaxis, :]
print(new_arr)
print(new_arr.ndim)

[0 1 2 3 4]
1
[[0 1 2 3 4]]
2


# Question 5

In [65]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[10,11,12],[13,14,15],[16,17,18]])
print("Vertical Stack\n",np.vstack((arr1,arr2)))
print("Horizantal Stack\n",np.hstack((arr1,arr2)))

Vertical Stack
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Horizantal Stack
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


# Question 6

In [66]:
import numpy as np
arr =np.array([9,1,1,0,54,30,4,6,30,7,88,14,6,4,0,9,49,23,49,31,32])
print(np.unique(arr),"\n",np.size(np.unique(arr)))

[ 0  1  4  6  7  9 14 23 30 31 32 49 54 88] 
 14
